// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkFaSofg2z3gyN3mDolfAD2juCul2N-PU',
    appId: '1:433609549622:web:fa5828440ed2076cfd3597',
    messagingSenderId: '433609549622',
    projectId: 'plugplay-98d28',
    authDomain: 'plugplay-98d28.firebaseapp.com',
    storageBucket: 'plugplay-98d28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdohTN6gNq09PMy98lE4PMzLf3wlPjpGc',
    appId: '1:433609549622:android:a770f0d2be51d9d2fd3597',
    messagingSenderId: '433609549622',
    projectId: 'plugplay-98d28',
    storageBucket: 'plugplay-98d28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0aHZVE5VBubQuvD2YhNMLi774wyZHg6g',
    appId: '1:433609549622:ios:ead0f1bb84d1bf4cfd3597',
    messagingSenderId: '433609549622',
    projectId: 'plugplay-98d28',
    storageBucket: 'plugplay-98d28.firebasestorage.app',
    iosBundleId: 'com.example.musicflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0aHZVE5VBubQuvD2YhNMLi774wyZHg6g',
    appId: '1:433609549622:ios:ead0f1bb84d1bf4cfd3597',
    messagingSenderId: '433609549622',
    projectId: 'plugplay-98d28',
    storageBucket: 'plugplay-98d28.firebasestorage.app',
    iosBundleId: 'com.example.musicflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkFaSofg2z3gyN3mDolfAD2juCul2N-PU',
    appId: '1:433609549622:web:50b032cb417e08c5fd3597',
    messagingSenderId: '433609549622',
    projectId: 'plugplay-98d28',
    authDomain: 'plugplay-98d28.firebaseapp.com',
    storageBucket: 'plugplay-98d28.firebasestorage.app',
  );
}
